# CMake generated Testfile for 
# Source directory: /workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib
# Build directory: /workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMakeLib.testArgumentParser]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestBinPacker]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceAllocator]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceSpec]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceGroups]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGccDepfileReader]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGeneratedFileStream]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testJSONHelpers]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRST]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testRST" "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRange]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testOptional]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testString]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testStringAlgorithms]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testSystemTools]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUTF8]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLParser]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLSafe]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testFindPackageCommand]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVProcessChain]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVRAII]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVStreambuf]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/bin/cmake")
set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtMemory]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtAlgorithm]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtEnumSet]=] "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLibTests" "testCMExtEnumSet")
set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;67;add_test;/workspace/clang-quickstart/code/cmake/cmake-3.26.4/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
