set(command "/usr/bin/cmake;-P;/workspace/linux/clang-quickstart/vscode/code/storage_project/index/demo/build_orc/orc/zlib_ep-prefix/src/zlib_ep-stamp/download-zlib_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/bin/cmake;-P;/workspace/linux/clang-quickstart/vscode/code/storage_project/index/demo/build_orc/orc/zlib_ep-prefix/src/zlib_ep-stamp/verify-zlib_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/bin/cmake;-P;/workspace/linux/clang-quickstart/vscode/code/storage_project/index/demo/build_orc/orc/zlib_ep-prefix/src/zlib_ep-stamp/extract-zlib_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
